# Generated by Django 5.2.3 on 2025-06-22 04:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ai_instructions', models.TextField(blank=True, help_text='Project-level instructions for AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ai_model', models.CharField(blank=True, help_text='AI model to use for this chat', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='api.project')),
            ],
            options={
                'db_table': 'chats',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('bio', models.TextField(blank=True)),
                ('user_memory', models.TextField(blank=True, help_text='User preferences for AI responses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('settings', models.JSONField(default=dict, help_text='Modular user settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], default='user', max_length=20)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('edited', 'Edited')], default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chat')),
                ('original_message', models.ForeignKey(blank=True, help_text='Reference to original message if this is an edit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_versions', to='api.message')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['chat'], name='messages_chat_id_1fd5a3_idx'), models.Index(fields=['role'], name='messages_role_8be1df_idx'), models.Index(fields=['status'], name='messages_status_72d01d_idx'), models.Index(fields=['created_at'], name='messages_created_919c58_idx'), models.Index(fields=['original_message'], name='messages_origina_0bdc4b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner'], name='projects_owner_i_c299b3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='projects_created_40bcd1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['updated_at'], name='projects_updated_ff62bb_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['owner'], name='chats_owner_i_f6ce0e_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['project'], name='chats_project_7e6a94_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['status'], name='chats_status_8b82ca_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['created_at'], name='chats_created_e8f0e7_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['updated_at'], name='chats_updated_9a6675_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='user_profil_user_id_fbe33d_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['created_at'], name='user_profil_created_26443b_idx'),
        ),
        migrations.AddIndex(
            model_name='usersettings',
            index=models.Index(fields=['user'], name='user_settin_user_id_33f61c_idx'),
        ),
        migrations.AddIndex(
            model_name='usersettings',
            index=models.Index(fields=['updated_at'], name='user_settin_updated_742bbf_idx'),
        ),
    ]
