# Generated by Django 5.2.3 on 2025-06-22 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='message_graph',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('head_message_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='api.chat')),
            ],
            options={
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('edit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prev_message_id', models.UUIDField()),
                ('new_message_id', models.UUIDField()),
                ('new_head_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='api.branch')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='api.chat')),
            ],
            options={
                'db_table': 'edit',
            },
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['chat'], name='branch_chat_id_393b34_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['head_message_id'], name='branch_head_me_1b4e66_idx'),
        ),
        migrations.AddIndex(
            model_name='edit',
            index=models.Index(fields=['chat'], name='edit_chat_id_ad1949_idx'),
        ),
        migrations.AddIndex(
            model_name='edit',
            index=models.Index(fields=['branch'], name='edit_branch__fd7898_idx'),
        ),
        migrations.AddIndex(
            model_name='edit',
            index=models.Index(fields=['prev_message_id'], name='edit_prev_me_13141b_idx'),
        ),
        migrations.AddIndex(
            model_name='edit',
            index=models.Index(fields=['new_message_id'], name='edit_new_mes_daaaaa_idx'),
        ),
        migrations.AddIndex(
            model_name='edit',
            index=models.Index(fields=['new_head_id'], name='edit_new_hea_6bbf42_idx'),
        ),
    ]
