# Generated by Django 5.2.3 on 2025-06-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chat_message_graph_branch_edit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='head_message_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message_graph',
            field=models.JSONField(blank=True, default=dict, help_text='Graph of message relationships: {id: {parent, children}}'),
        ),
    ]
